### ISSUE TITLE
Unable to remove member from group

### ISSUE THREAD

**Issue by dawidry** [TICESoftware/about#10]
App Platform: iOS

Bug reproduction:
1. Create group (iOS)
2. Send inviatation (iOS)
3. Join (e.g.Andorid, Desktop)
4. Go to Group Info -> Members list (iOS)
5. Try to remove recently joined user
Error pop-up appears:
![Screenshot 2021-12-22 o 22 36 24](https://user-images.githubusercontent.com/13475936/147159137-d2ad10db-b7b3-4322-8d1e-c400d7ed81dc.png)

**Comment by code28** [comment]
Hi @dawidry,

thanks again for posting this issue, too. It's fixed and deployed as well.
