### ISSUE TITLE
Unable to remove group

### ISSUE THREAD

**Issue by dawidry** [TICESoftware/about#12]
Platform: iOS

1. Create group
2. Add members
3. Try to remove group

![IMG_031CBA4D9C6D-1](https://user-images.githubusercontent.com/13475936/147160342-81a73832-89da-4b6d-b291-cd9b6dc90773.jpeg)

**Comment by code28** [comment]
Hi @dawidry,

thanks for bringing this topic up.

We fixed it and the fix is deployed now, so you should be able to remove groups again.

**Comment by dawidry** [comment]
Hi, 
I did test. It's works as expected now. Great job. I appreciate it.
