### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Droidphilev** [TICESoftware/about#7]
Hi,

I gave your app a try. It seems i found 2 problems:

- Eventough the app is open but i'm not sharing location the GPS antenna stays in use.
- After closing the app the GPS antenna also stays in use. Only killing/force stoppin the app disables the GPS.
This will eat battery i'm afraid.

Request:
Also make it possible to use different levels of accuracy. Traccar client for example has 3 levels. I never use the lowest one but medium uses no GPS antenna but only network location, High uses the antenna also. Sometimes network location would be enough + the app be used much longer this way.

Tested on OnePlus 9 Pro with Android 11.

**Comment by ChaosCoder** [comment]
This is tracked in [TICESoftware/tice-android#29](https://github.com/TICESoftware/tice-android/issues/29), closing this issue here.
